### ISSUE TITLE
ModuleNotFoundError no module named pandas

### ISSUE THREAD

**Issue by kenseii** [MIERUNE/GTFS-GO#22]
Environment: 
  - Ubuntu 20.04
  - QGIS 3.16.3

By default on linux, qgis doesn't have pandas installed in its environment so it is necessary to include it in the install script of the plugin.

Without pandas the plugin will raise a `ModuleNotFoundError` when installing it in the qgis interface.

**Comment by e471wo** [comment]
hi, I have the issue...
I installed pandas (pip install pandas, etc...), pandas is installed (on a terminal, I can launch python and do import pandas), but when I try to import the plugin I sill have the issue. 
Am I doing wrong something ? thanks (I use the flatpak package 3.38.3-Grenoble)
thanks

```
Couldn't load plugin 'GTFS-GO-master' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'pandas' 
Traceback (most recent call last):
  File "/app/share/qgis/python/qgis/utils.py", line 426, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/elekis/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/GTFS-GO-master/__init__.py", line 8, in classFactory
    from .gtfs_go import GTFSGo
  File "/app/share/qgis/python/qgis/utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/elekis/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/GTFS-GO-master/gtfs_go.py", line 8, in 
    from .gtfs_go_dialog import GTFSGoDialog
  File "/app/share/qgis/python/qgis/utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/elekis/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/GTFS-GO-master/gtfs_go_dialog.py", line 27, in 
    from .gtfs_parser import gtfs_parser
  File "/app/share/qgis/python/qgis/utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/elekis/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/GTFS-GO-master/gtfs_parser/gtfs_parser/__init__.py", line 1, in 
    from .gtfs import GTFSFactory, GTFS
```
