### ISSUE TITLE
Datalist JSON parsing error

### ISSUE THREAD

**Issue by Kanahiro** [MIERUNE/GTFS-GO#37]
```
2021-06-04T16:28:34     WARNING    Traceback (most recent call last):
File "/Users/USERNAME/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/GTFS-GO-master/gtfs_go.py", line 212, in run
self.dialog = GTFSGoDialog(self.iface)
File "/Users/USERNAME/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/GTFS-GO-master/gtfs_go_dialog.py", line 59, in __init__
self.datalist = json.load(f)
File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/json/__init__.py", line 293, in load
return loads(fp.read(),
File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 53: ordinal not in range(128)
```

**Comment by Kanahiro** [comment]
In macOS with 3.16.0, this error doesn't occur.
In 3.16.0, python version is 3.7.7, in 3.16.5 (above), is 3.8. I assume this deference might make error.
