### ISSUE TITLE
Error GTFS GO

### ISSUE THREAD

**Issue by Rossellaross87polito** [MIERUNE/GTFS-GO#70]
An error occurred while running the Python code:
FileNotFoundError: calendar is not exists.
Traceback (most recent call last):
File "C:\Users/rosse/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GTFS-GO-master\gtfs_go_dialog.py", line 237, in execution
gtfs_parser = GTFSParser(extracted_dir)
File "C:\Users/rosse/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GTFS-GO-master\gtfs_parser_main_.py", line 35, in init
self.dataframes = self._load_tables(txts)
File "C:\Users/rosse/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GTFS-GO-master\gtfs_parser_main.py", line 64, in __load_tables
raise FileNotFoundError(f"{datatype} is not exists.")
FileNotFoundError: calendar is not exists.

Versione Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May 3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
Versione di QGIS: 3.28.6-Firenze Firenze, https://github.com/qgis/QGIS/commit/868c9fa03b1ac4cfeabf2a3badf5cad6281e8eb6

Percorso Python:
C:/PROGRA1/QGIS321.6/apps/qgis-ltr/./python
C:/Users/rosse/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/rosse/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA1/QGIS321.6/apps/qgis-ltr/./python/plugins
C:\PROGRA1\QGIS321.6\apps\grass\grass82\etc\python
C:\Program Files\QGIS 3.28.6\bin
C:\Program Files\QGIS 3.28.6\bin\python39.zip
C:\PROGRA1\QGIS321.6\apps\Python39\DLLs
C:\PROGRA1\QGIS321.6\apps\Python39\lib
C:\PROGRA1\QGIS321.6\apps\Python39
C:\PROGRA1\QGIS321.6\apps\Python39\lib\site-packages
C:\PROGRA1\QGIS321.6\apps\Python39\lib\site-packages\win32
C:\PROGRA1\QGIS321.6\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA1\QGIS321.6\apps\Python39\lib\site-packages\Pythonwin
C:/Users/rosse/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\rosse\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
.
here is the gtfs i tried to upload
[gtfs_compressed.zip](https://github.com/MIERUNE/GTFS-GO/files/11573006/gtfs_compressed.zip)

**Comment by Kanahiro** [comment]
Thank you for report. I can reproduce the problem but for me "agency is not exists" 🤔

**Comment by takohei** [comment]
Cause:
This error occurs because there are no records in calendar.txt.

Expected:
calendar.txt is not required, if calendar_dates.txt contains all days.
https://gtfs.org/schedule/reference/#dataset-files
Therefore, the error should not occur.

Action:
I will fix it to allow for the lack of files and fields, along with other similar issues.
