### ISSUE TITLE
Fix missing feed_info.txt error

### ISSUE THREAD

**Issue by takohei** [MIERUNE/GTFS-GO#80]
`feed_info.txt` is not a required file.
However, an error occurres if `feed_info.txt` is missing.

This is regression of #15, #16

An example of data that does not work is [Yakima Transit](https://yakimatransit.org/gtfs/yakima_gtfs.zip).

The traceback log is as follows.
```
Traceback (most recent call last):
  File "C:/dev/items/GTFS-GO/test_diff/diff_feed.py", line 91, in read_feed
    tgt_date = get_feed_start_date(gtfs_path)
  File "C:/dev/items/GTFS-GO/test_diff/diff_feed.py", line 14, in get_feed_start_date
    with gtfs_zip.open('feed_info.txt', 'r') as feed_info_file:
  File "C:\Users\oh\AppData\Local\Programs\Python\Python36\lib\zipfile.py", line 1352, in open
    zinfo = self.getinfo(name)
  File "C:\Users\oh\AppData\Local\Programs\Python\Python36\lib\zipfile.py", line 1281, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named 'feed_info.txt' in the archive"
```

I will fix this in the near future, please wait a moment.

**Comment by takohei** [comment]
Sorry, this was my misunderstanding.
